version: 1.3
workflows:
   - name: AlignSample
     subclass: WDL
     publish: True
     primaryDescriptorPath: /wdl-workflows/alignSample.wdl
     testParameterFiles:
         - /wdl-workflows/alignSample.inputs.json
     authors:
         - name: "Grant Daly"
           orcid: "0000-0002-4109-0546"
           email: "daly@southalabama.edu"
           role: "Graduate Student"
           affiliation: "University of South Alabama College of Medicine"
     filters:  
         tags:
             - /.*/
         branches:
             - master

   - name: PostProcess
     subclass: WDL
     publish: True
     primaryDescriptorPath: /wdl-workflows/postProcessAlignments.wdl
     testParameterFiles:
         - /wdl-workflows/postProcessAlignments.inputs.json
     authors:
         - name: "Grant Daly"
           orcid: "0000-0002-4109-0546"
           email: "daly@southalabama.edu"
           role: "Graduate Student"
           affiliation: "University of South Alabama College of Medicine"
     filters: 
         tags:
             - /.*/
         branches:
             - master

   - name: CallPileup
     subclass: WDL
     publish: True
     primaryDescriptorPath: /wdl-workflows/generatePileup.wdl
     testParameterFiles:
         - /wdl-workflows/generatePileup.inputs.json
     authors:
         - name: "Grant Daly"
           orcid: "0000-0002-4109-0546"
           email: "daly@southalabama.edu"
           role: "Graduate Student"
           affiliation: "University of South Alabama College of Medicine"
     filters:
         tags:
             - /.*/
         branches:
             - master

