version: 1.2
workflows: 
  - name: alignSamples
    primaryDescriptorPath: /wdl-workflows/alignMultipleSamples.wdl
    testParameterFiles: 
      - /wdl-workflows/alignMultipleSamples.inputs.json
    subclass: WDL
