version: 1.2
workflows:
   - name: AlignSample
     subclass: WDL
     publish: True
     primaryDescriptorPath: /wdl-workflows/alignSample.wdl
     testParameterFiles:
         - /wdl-workflows/alignSample.inputs.json
     authors:
         - name: "Grant Daly"
           orcid: "0000-0002-4109-0546"
           email: "daly@southalabama.edu"
           role: "Graduate Student"
           affiliation: "University of South Alabama College of Medicine"
     filters:  
         tags:
             - /.*/
         branches:
             - master
             - oneSample
   - name: PostProcess
     subclass: WDL
     publish: True
     primaryDescriptorPath: /wdl-workflows/post-process-alignments.wdl
     testParameterFiles:
         - /wdl-workflows/post-process-alignments.inputs.json
     authors:
         - name: "Grant Daly"
           orcid: "0000-0002-4109-0546"
           email: "daly@southalabama.edu"
           role: "Graduate Student"
           affiliation: "University of South Alabama College of Medicine"
     filters: 
         tags:
             - /.*/
         branches:
             - master
             - oneSample
   - name: CallHeteroplasmies
     subclass: WDL
     publish: True
     primaryDescriptorPath: /wdl-workflows/call-heteroplasmies.wdl
     testParameterFiles:
         - /wdl-workflows/post-process-alignments.inputs.json
     authors:
         - name: "Grant Daly"
           orcid: "0000-0002-4109-0546"
           email: "daly@southalabama.edu"
           role: "Graduate Student"
           affiliation: "University of South Alabama College of Medicine"
     filters:
         tags:
             - /.*/
         branches:
             - master
             - oneSample
