version: 1.2
workflows:
   - name: alignSamples
     subclass: WDL
     publish: True
     primaryDescriptorPath: /wdl-workflows/alignMultipleSamples.wdl
     testParameterFiles:
         - /wdl-workflows/alignMultipleSamples.inputs.json
     filters:  # All tags, no branches
         tags:
             - /.*/
         branches:
             - master
